### ISSUE TITLE
Amiga Emulation - only Disk or black screen

### ISSUE THREAD

**Issue by MasteRehm** [petrockblog/RetroPie-Setup#247]
Hi,

I opened already a post at your forum [3], but I'm of the opinion that it fits better here.

I’m using the latest Retropie SD Image. Updated the _raspbian_ Distro, _retropie_setup.sh_ Script and the _RetroPie Binaries_.
Afterwards I followed the Wiki Instruction [1] about the Amiga emulation (slightly difference: uae4rpi instead of uae4all) and copied the kick.rom under /home/pi/RetroPie/emulators/uae4rpi/ and the gamerom file under /home/pi/RetroPie/emulators/uae4rpi/roms.
I start the Amiga emulation as follows:
```
cd /home/pi/RetroPie/emulators/uae4rpi
./uae4all
```

Either I get the typical Hand/Disk-Image (e.g. [2]) or a black screen. In the typical screen no keyboard input is recognized. I only see three color symbols in the bottom right corner: one red, and two green with numbers. The first green one change from 00 to 01 after a few seconds and vice versa.

Seems to be a bug.

[1] https://github.com/petrockblog/RetroPie-Setup/wiki/Amiga-emulator-%28UAE4All%29
[2] http://www.ravn.de/contentfiles/Image/blog/amiga_workbench.jpg
[3] http://blog.petrockblock.com/forums/topic/amiga-emulation-only-disk-or-black-screen/

**Comment by joolswills** [comment]
should work with the latest retropie-setup image - make sure you have enabled dispmanx for uae4all in the setup menu.

**Comment by petrockblog** [comment]
Would it make sense to enable Dispmanx per default for all emulators that we know benefit from it?

**Comment by joolswills** [comment]
It may make sense to change the default to on yeh.

**Comment by joolswills** [comment]
I've just been fixing up problems with vice in regarding to similar issues - and have enabled dispmanx by default for that (and have fixed it from crashing without also) - currently the default is dispmanx, but the performance is better without (but with tearing).

**Comment by joolswills** [comment]
Note to original poster, this is fixed now - but you will need to launch uae4all via the startAmigaDisk.sh script or dispmanx won't be enabled (and it could freeze/crash then)
