### ISSUE TITLE
"Couldn't open joystick #0" when running retroarch-joyconfig

### ISSUE THREAD

**Issue by denny2k2** [petrockblog/RetroPie-Setup#305]
Hi all,

I am trying to set up a wired 360 controller.  I have it working in emulationstation menu no problem, can scroll, select roms etc.  I am now trying to set it up for play in game.  I have tried going to the "Input Configuration" menu from emulationstation.  It recognises my controller and I run through the prompts.  I select all 3 emulators, map my buttons and when I try and save I get the message "Script Error!".

So I tried going into retroarch-joyconfig from command line and I get the error "Couldn't open joystick #0".

Any ideas how I can solve this issue and get my xbox 360 wired controller working for gameplay?

Many thanks in advance.

**Comment by joolswills** [comment]
is this still an issue with the latest image/retropie-setup ?
