### ISSUE TITLE
Add setting to disable copyroms script

### ISSUE THREAD

**Issue by MelGrubb** [petrockblog/RetroPie-Setup#393]
I plan to keep my ROMs on the external storage, and don't want them copied to the SD card, since it has the potential to fill up the card rather quickly. I can, of course, disable the script manually, but I'm worried that a future update will restore the script, and fill up my card again. I'd prefer a setting in a config file that would survive updates.

I'm working around the problem for now by putting my roms in a sub-folder (/RetroPie/roms), and leaving the /roms folder empty. This solves the space problem, but still has the habit of creating folders on any drive I plug in.

Some slightly different behavior might eliminate this problem. If a drive already HAS a root-level folder called "roms", then the script could go ahead and copy things from it, and maybe even create missing folders so that users have a structure to put things in. If the drive does NOT already have a "roms" folder, then the script could just bail out. This would maintain the ease of use, but without adding folders to every drive that gets plugged in.

**Comment by joolswills** [comment]
There is an option in retropie-setup now to enable/disable the usbromservice. in regards to your functionality change, this is planned - it will sync only when there is a roms folder - please check https://github.com/petrockblog/RetroPie-Setup/issues/619
