### ISSUE TITLE
SDL2 doesn't support retrogame :(

### ISSUE THREAD

**Issue by ladyada** [petrockblog/RetroPie-Setup#397]
Hi there has been some frustration that RetroPi 2+ added SDL2 but inadvertently dropped support for GPIO-based EVDEV keycode fun such as used in 'retrogame' 

https://github.com/adafruit/Adafruit-Retrogame/issues/5

HowTo patch here thx to @CrazySpence!
https://github.com/adafruit/Adafruit-Retrogame/issues/5#issuecomment-49942096

Is this something that can be fixed up in a future release? Alternatively we'll try to track down a retropie 1.9.1 image and just point people to that

**Comment by joolswills** [comment]
retropie-setup now comes with sdl 2.0.3 so this should be fixed. Please can you check/confirm
