### ISSUE TITLE
runcommand and mode selection

### ISSUE THREAD

**Issue by joolswills** [petrockblog/RetroPie-Setup#531]
I have some changes for runcommand.sh that seem logical and solve an issue in my case, but wanted to go over some details.

a) fbset -depth 8 && fbset -depth 16

Why is this needed? It first tries to set 8 bit depth, and if that succeeds it tries a 16 bit depth ? Are there cases where 16 bit will fail ?

b) starttype==1: set video mode to VGA ONLY IF tvservice is in HDMI mode, and run command

This mode is 4:3 ratio even on 16:9 monitors I believe ? Currently this mode is used for a bunch of emulators - but if on a 19:6 monitor mode 3 (mode 3: 720x480 @ 60Hz 16:9, clock:27MHz progressive) would seem a better choice to keep the correct aspect ratio ?

c) starttype 2 / 3 / 6 / 7 / 8 are not used by anything. Do they serve any purpose ?

--

Basically the changes I want to make are to take into account the preferred mode of the monitor, and record the aspect and group of that and use that as a basis for mode choice. My picade monitor is 1024x768, and the preferred mode is "state 0x12001a [HDMI DMT (16) RGB full 4:3], 1024x768 @ 60.00Hz, progressive". Some of the current emulators try to use starttype 4 (set video mode to 720p60 ONLY IF tvservice is in HDMI mode and run command) - which is unsuitable for a 4:3 monitor like mine. My changes would only allow this mode to be selected if the monitor preferred mode is the same aspect. In the case of my monitor, the preferred mode is a better choice.

If you could help me with some of these questions, I can make sure I don't break any existing functionality in use, but make runcommand work better for 4:3 and 16:19

**Comment by gizmo98** [comment]
We need runcommand.sh to lower resolution because some emus (mostly libretrocores) slow down at 1080p. I have pushed another way to lower render resolution of retroarch without changing the display/framebuffer resolution. The pi can upscale any source to the frambuffer resolution for free --> https://github.com/libretro/RetroArch/pull/1308

All libretrocores can be run with "runcommand.sh 0". The render resolution can be set in retroarch.cfg with video_fullscreen_x and video_fullscreen_y. If both values are zero retroarch uses the display resolution (old behavior).

Upscaling can be tuned with boot arguments:
https://github.com/raspberrypi/firmware/issues/104

**Comment by joolswills** [comment]
A step forward definitely - thanks - but I think this adds some more configuration problems unless I have misunderstood? 

Right now with the latest runcommand.sh a resolution can be set per emulation/per rom by the user (and saved) (based on what their screen supports). If we switch to runcommand 0, and change the fullscreen_x/fullscreen_y, won't we have another value to configure in retroarch.cfg / for each core config, unless you think it is possible to set these width/height to a sensible value per core that will be good for all users no matter their output res. I'm just thinking whether switching over to this improves stuff right now or not. 

I have been using 640x480 for most retroarch emulators (changing with the gui). So I think the current runcommand.sh 4 is not ideal also (especially when an effects shader is used).

Switching to a lower screenmode should reduce memory usage also though too I would think ?

Just trying to think how this will all play nicely together.

**Comment by gizmo98** [comment]
It is output resolution independent and you can use lower resolutions (<640*480) for sensible emulators. Or you can set the original resolution of an emulated system. I just use a fixed WVGA resolution atm (fullscreen_x=800 fullscreen_y=480). Otherwise dispmanx will scale a 4:3 image (640*480) to a 16:9 (1080p) resolution. Think about it. It's one more option we can use.

**Comment by joolswills** [comment]
I get the bit regarding setting an original resolution. Makes sense for that, but won't that mess up the shaders ? Won't they then get rendered at the lower resolution - I would have though the shaders should be rendered at the current screen resolution ?

**Comment by joolswills** [comment]
(or some of them at least). Anyway, as you say it's one more option - but we need to come up with a way to make it configurable etc.

Right now I'm keen to switch all the retroarch emulators to runcommand 1, so they default to 640x480

**Comment by gizmo98** [comment]
Some shaders need higher resolutions because otherwise you cannot see any effect. But 720p is the highest resolution we can use. Resolutions above 720p + shaders are slow as hell.

And some cores could benefit from a resolution with an even scaling factor. For example game boy resolution (160*144)*4 = 640*576.

I haven't found a way to tell retroarch over commandline to use a resolution. Use iniSet in runcommand.sh seems to be a dumb idea.

**Comment by gizmo98** [comment]
I tried to compare Mario Kart with 720p, 720p with a render resolution of 800x480 and 1080p with a render resolution of 800x480. There was no significant difference. I will check with another game.

**Comment by joolswills** [comment]
we currently make a temporary cfg file for retroarch from runcommand that contains the refresh rate, so potentially a resolution could be included also, however we will need to come up with a non confusing way for users to configure/set up. Perhaps an additional menu entry for users to change so they have control over both screenmode/refresh and the render resolution.

**Comment by gizmo98** [comment]
@joolswills 
Hardware upscaling respects aspect ratio now https://github.com/libretro/RetroArch/commit/9f40b65fcaa2994b4fbb344fbbe2fdc27596647f.
You can set fullscreen_x=640 fullscreen_y=480. The width will be recalculated if you have a video output resolution with another aspect ratio.

**Comment by joolswills** [comment]
your code seems to make an assumption regarding source size and only ever adjusts X - couldn't that cause the wrong size in some cases - it should surely check both X and Y? 

here is the way I have done it with sdl.

```
float width_scale, height_scale;
width_scale = (float) dispvars->amode.width / width;
height_scale = (float) dispvars->amode.height / height;
float scale = min(width_scale, height_scale);
int dst_width = width * scale;
int dst_height = height * scale;
int dst_xpos = (dispvars->amode.width - dst_width) / 2;
int dst_ypos = (dispvars->amode.height - dst_height) / 2;
```

**Comment by joolswills** [comment]
(which is basically this - http://codereview.stackexchange.com/a/70916)

**Comment by gizmo98** [comment]
I do not work with scale. I multiply the calculated screen aspect ratio with source_y to get proper source_x. Example:
-Screen is 1080p. Calculated aspect is 1.77776. source_y = 480 --> source_x = 853
-Screen is VGA. Calculated aspect is 1.3333. source_y = 480 --> source_x = 640
-Screen 90° rotated VGA. Calculated aspect is 0.75. source_y = 480 --> source_x = 360

So the source has always the same aspect as the screen. I could modify the coding so source_x will be at least >= fullscreen_x for aspects <= 1.33. I don't now if this. Should be something like:


if (srcAspect != dstAspect)
{   
  *width = (unsigned)(g_settings.video.fullscreen_y * dstAspect);
  if (*width < g_settings.video.fullscreen_x)
  {
     *width = g_settings.video.fullscreen_x;
     *height = (unsigned)(g_settings.video.fullscreen_x / dstAspect);;
  }
}

**Comment by gizmo98** [comment]
I have to take a look at your sdl coding because i don't know why you calculate destination width, height and position. Retroarch and gpsp always use the whole screen as destination.

**Comment by joolswills** [comment]
oh I see - you are calculating the render resolution from the screen res/aspect? or ?

I was thinking this would work the other way around - you set a render res of say 640x480, it's correctly rendered at that resolution (with configured aspect ratio), and then just scaled up to fit the monitor - using the smallest scale so nothing is off the screen.

**Comment by gizmo98** [comment]
There is nothing off the screen. Dispmanx strechs a source rect always to a destination rect and does not respect aspect ratios. You could do interesting anamorphic experiments with dispmanx.

**Comment by joolswills** [comment]
There would be something off the screen if in my example code the smallest ratio wasn't checked (code to scale from small to large). That is what I am referring to.

**Comment by joolswills** [comment]
It's just we are doing things the other way around. you are adjusting the render resolution based on the screen resolution. My code has a set render resolution, and chooses how to scale that up to fit the screen - hence the offsets for the destination.

**Comment by joolswills** [comment]
(or at least that is how I am reading it from what you said). I just think I would do it in a different way, but I'll take a look and maybe have a play as I may be misunderstanding.

**Comment by gizmo98** [comment]
Retroarch actually does not use vc context source resolution for rendering. It is smart enough do calculate a custom viewport width/height and xpos/ypos. 
-Screen = 1080p. srcRect = 853x480 --> custom_viewport = 640x480 custom_viewport_xpos=106
-Screen = 720p. srcRect = 853x480 --> custom_viewport = 640x480 custom_viewport_xpos=106
-Screen is VGA. srcRect = 640x480 --> custom_viewport = 640x480 custom_viewport_xpos=0

Your solution is really nice if the emulator does not care about correct aspect ratios. Mupen64plus video plugins do not respect game aspect ratios and stretch the whole screen if you set 1080p. It would be nice if we could add your solution to https://github.com/spurious/SDL-mirror/blob/master/src/video/raspberry/SDL_rpivideo.c#L246.

**Comment by gizmo98** [comment]
Do you think it is ready to go? I would like to add something like:
set runcommand 0 for all libretrocores 

/opt/retropie/configs/all/retroarch.cfg:
if isPlatform "rpi1":
video_fullscreen_x=640 
video_fullscreen_y=480
if isPlatform "rpi2":
video_fullscreen_x=960 
video_fullscreen_y=720

PI2 is still not fast enough if you use shaders and 1080p.

**Comment by joolswills** [comment]
I would like to do a little testing myself first.

Do any emulated machines need 960x720 or do the shaders just look better then ?

**Comment by gizmo98** [comment]
Overlays and shaders look better. If you have a LCD TV try to use the old TV overlay :-) You can find overlay presets under RGUI/Settings/OverlaySomething/Presets.

**Comment by joolswills** [comment]
I think it would be nice if we can offer the users the ability to change the render resolution - perhaps it would be enough to set it to 640x480 but then allowing it to be configured via the runcommand menu as the video resolution is?

**Comment by joolswills** [comment]
I could add support for that first, and then we could make these changes after (and after some more testing from my end as I haven't yet had a chance to try it).

**Comment by joolswills** [comment]
I believe this can be closed now - all seems to be working well. Please open a new ticket if anything crops up. Thanks for all the help with this gizmo98.
