### ISSUE TITLE
Dosbox compiles during binaries-based installation

### ISSUE THREAD

**Issue by petrockblog** [petrockblog/RetroPie-Setup#546]
DOSBox compiles during binaries-based installation. This should not be done.

**Comment by joolswills** [comment]
aah. left over code that wasn't removed with dosbox previously (dosbox was removed, then re-added as I worked out how to compile it with dynamic recompilation, and also that fastdosbox was not what it claimed to be).

**Comment by joolswills** [comment]
fixed.
