### ISSUE TITLE
Atari Lynx rom folder name should be "atarilynx"

### ISSUE THREAD

**Issue by ProxyCell** [petrockblog/RetroPie-Setup#548]
I was browsing the official Emulation Station website today and found their list of systems. It lists the atari lynx as "atarilynx" and not as "lynx" which is the current name for the rom folder for that system.

Would it be possible to change this folder name to atarilynx to not only be in line with ES but for consistency when themes for this system are released?

**Comment by joolswills** [comment]
merged so closing. thanks all
