### ISSUE TITLE
Backup and restore ROMS, BIOS, and CONFIG files

### ISSUE THREAD

**Issue by petrockblog** [petrockblog/RetroPie-Setup#562]
The following idea [came from a user](http://blog.petrockblock.com/forums/topic/retropie-2-x-feedback-enhancements/#post-84754):

_[...] What may also be beneficial is an easy backup solution where only the main directories are backed up into a tar.gz or zip file. This file could be transferred to another ‘stock image’ and using the script, a restore option could be run which would populate all of the folders (roms, bios and configs) to the new installation based on the old._

**Comment by KitchUK** [comment]
If this is possible it would make upgrading to new version ALOT easier, especially for non advanced users.

**Comment by robertybob** [comment]
Images, bios, configs and gamelists I definitely agree with. Roms however I'm not sure about- what if a person has PS1 and SNES roms alongside NES and Genesis ..that's going to take a long long time to backup ..or you'll have to have an option to specify which roms too back up.

**Comment by robertybob** [comment]
Bump. Any news on this @petrockblog ?

**Comment by joolswills** [comment]
the usbromservice now has a facility to back up/restore the emulation station custom custom/gameslists etc More configs will be added later.

**Comment by Shawson** [comment]
Hey, did the config files element of this ever get going?  I use the usb rom service and my roms/ bios etc run from the hdd, but my configs folder is still on the sd card along with game save etc?
