### ISSUE TITLE
RetroPie - USB gamepad working in emulation station but not in ROMS

### ISSUE THREAD

**Issue by RFKirb** [petrockblog/RetroPie-Setup#564]
Firstly, thank you for taking the time to read my thread. Here's my current setup:

System: Raspberry Pi B+
SD: SanDisk Ultra 32GB
Distro: RetroPie v2.3
Gamepads: 2x SNES Retro USB Super Nintendo Controller (http://www.amazon.com/gp/product/B0034ZOAO0/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)

As the title states, I can use either of my USB gamepads in emulation station just fine, but when I launch a ROM neither work, but the default keyboard bindings work. I followed the instructions here (https://github.com/petrockblog/RetroPie-Setup/wiki/Control-Issues) for USB gamepads, which listed the below commands:

$ /opt/retropie/emulators/RetroArch/installdir/bin/retroarch-joyconfig -a /opt/retropie/emulators/RetroArch/configs/gamepad.cfg

The command executes fine, and I am able to use the tool to output the gamepad.cfg file, but again, upon entering a ROM (SNES or NES) both gamepads are unresponsive. What should be my next step? I appreciate your help.

**Comment by ProxyCell** [comment]
ok, you're using a fresh 2.3 image right? have you ran the "update scripts"?
i have multiples of this EXACT controller. i just ran the "Register RetroArch Controller" to get the correct config for it originally

**Comment by RFKirb** [comment]
Yup, fresh 2.3 image. I'll try that when I get home.

**Comment by ProxyCell** [comment]
let us know the results when you do

**Comment by gizmo98** [comment]
The current folder names are:
$ /opt/retropie/emulators/retroarch/tools/retroarch-joyconfig -a /opt/retropie/emulators/retroarch/configs/gamepad.cfg

instead of

$ /opt/retropie/emulators/RetroArch/installdir/bin/retroarch-joyconfig -a /opt/retropie/emulators/RetroArch/configs/gamepad.cfg

**Comment by ProxyCell** [comment]
@gizmo98 
for 2.3?

**Comment by gizmo98** [comment]
Current! If you update RetroPie-Setup or if you use Retropie 2.4 Beta ;-)

**Comment by RFKirb** [comment]
So I updated the binaries and scripts, then configured the configure retroarch controller from the retropie setup, and it worked. Can I use it again to configure a second controller? Thanks everyone for your help.

**Comment by ProxyCell** [comment]
yeah i guess but is that 2nd controller the same?? if it is then you don't have to do anything extra

**Comment by RFKirb** [comment]
Yeah, but the .cfg file splits it out by controller #, so you can
potentially use different types (SNES, N64, etc). That being said, I know I
can copy the text from controller #0 and paste it to controller #1, but
using the utility would be easier.

**Comment by lomiccw1** [comment]
I had this issue and had to copy the .cfg file generated in $ /opt/retropie/emulators/retroarch/configs to $ /opt/retropie/emulators/RetroArch/configs  - why the split? I don't get the difference. I understand the directories are case sensitive, but what is the diff between RetroArch & retroarch?

**Comment by joolswills** [comment]
/opt/retropie/emulators/RetroArch/configs is the old location. Your install is out of date.

**Comment by joolswills** [comment]
Recommend you download the 2.4 beta image and go from there

**Comment by joolswills** [comment]
(alternatively, you should remove /opt/retropie completely and do a fresh binaries install from the latest setup script)

**Comment by ProxyCell** [comment]
hey @joolswills have you posted it elsewhere?

**Comment by joolswills** [comment]
it is available from http://blog.petrockblock.com/retropie/retropie-downloads/

**Comment by lomiccw1** [comment]
Awesome! thank you so much.

**Comment by lomiccw1** [comment]
Sorry, this might not be the correct spot to ask, but: are the install binaries still updated? I have seen info that indicated that the  pre-compiled binaries were no longer supported by Github. 

https://github.com/petrockblog/RetroPie-Setup

"Binaries and Sources:
RetroPie Setup offered the possibility to only install RetroArch, the cores, EmulationStation, and SNESDev with pre-compiled binaries. Since Github has discontinued the download service the option for installing pre-compiled binaried with the RetroPie script was discarded. Take your time and let RetroPie Setup download and compile the programs from their sources!"

**Comment by joolswills** [comment]
It is the wrong place to ask - open a new ticket or use the forum - or else issues will get very confusing. the binaries are updated.

**Comment by GuGuss** [comment]
Hi,

I'm having the same issue here with exactly the same controllers/Pi. I can use the gamepads in the EmulationStation, but not in any roms (only the keyboard works).

I've installed the image that I downloaded from here: http://blog.petrockblock.com/retropie/retropie-downloads/download-info/retropie-sd-card-image-for-rpi-version-1/

Any idea?

**Comment by ProxyCell** [comment]
hmm, can you go into the source-build menu? disable everything except for the "retroarchautoconf - RetroArch-AutoConfigs" near the bottom.

that should install the controller configs for you

**Comment by ias2** [comment]
Hi, I've the same problem. The only way to get the joystick working is to connect the ethernet cable to raspberry (!). What is the relationship between the joystick and the lan?

**Comment by joolswills** [comment]
This issue is closed - please use the forum for support.
