### ISSUE TITLE
Double rom folders

### ISSUE THREAD

**Issue by ProxyCell** [petrockblog/RetroPie-Setup#566]
This is a query about some "double rom folders"
fba and fba-libretro
pcengine and pcengine-libretro (both are libretro)

Is the intention to do this for other emulators down the line so people can pick their own emulator but have double the roms?

While this isn't a terrible idea there is currently no way for the user in Emulatation Station to determine which emulator is which. Could this be done with themes?

If this is not the intention then are these to be merged like other how every other system is currently handled, one roms folder with the es_systems.cfg managing who loads the roms.

I have attached a screenshot of roms directory

![screen_shot_2015-01-08_at_1_56_52_pm](https://cloud.githubusercontent.com/assets/3400448/5668541/65808984-973e-11e4-935e-48eb90d48ed4.png)

**Comment by joolswills** [comment]
it is so people can use one emulator or another for stuff yeh.

you are right it's confusing on emulationstation - I raised this upstream, and was given a solution, but it requires customisation of the theme to do some duplication and some additional includes. It is something I plan to look into.

See here for details

https://github.com/Aloshi/EmulationStation/issues/317

**Comment by ProxyCell** [comment]
thanks joolswills - i look forward to seeing that develop
what about the roms themselves? is it possible to have them placed into one single roms folder, then pick the emulator you prefer by switching to the differently themed group in ES? it would cut disk space usage in half while you use multiple emulators

**Comment by joolswills** [comment]
no, but you can cut disk usage by symlinking folders if you want to keep complete rom sets in each folder.

**Comment by ProxyCell** [comment]
thanks!
