### ISSUE TITLE
Script broken since recent update

### ISSUE THREAD

**Issue by musyne** [petrockblog/RetroPie-Setup#571]
Hi,
Yesterday it worked fine.
Today when I run a normal binary install on a fresh raspbian, EmulationStation says that no system are configured.

**Comment by joolswills** [comment]
did you update the script today ?

please try running the binaries install, and uploading the install log somewhere for me. thanks.

**Comment by joolswills** [comment]
(please update the script first)

**Comment by joolswills** [comment]
(in the meantime, I will try and replicate the problem on a fresh install)

**Comment by joolswills** [comment]
I found a major problem that happened due to the order of a few lines of code that got changed (by me). Yes, I broke it.

Please update the script, and try again and it should set things up correctly.

**Comment by musyne** [comment]
thanks :)

**Comment by joolswills** [comment]
Is it working ok for you again ?

**Comment by musyne** [comment]
Yes.
