### ISSUE TITLE
unable to resolve host retropie? - 2.4Beta

### ISSUE THREAD

**Issue by ProxyCell** [petrockblog/RetroPie-Setup#573]
If I ever execute the sudo command I will see the following:
sudo: unable to resolve host retropie

**Comment by joolswills** [comment]
aha. yeh. i forgot to add retropie to /etc/hosts

I'll have to push out a new image. in the meantime you can do

sudo sed -i "s/raspberrypi/retropie/" /etc/hosts

**Comment by ProxyCell** [comment]
thanks!
