### ISSUE TITLE
Amiga emulation still broken in 2.4 beta

### ISSUE THREAD

**Issue by stsfin** [petrockblog/RetroPie-Setup#576]
The amiga emulation does not start, gives only black screen and only way to quit is to pull the plug. The good thing is it seems that the symbolic link is now working which did not work correctly in 2.3.  Any ideas?

**Comment by joolswills** [comment]
Go to retropie-setup and choose "configure emulators to use dispmanx" and enable it for uae4all

**Comment by stsfin** [comment]
@joolswills that did the trick, this setting could be enabled by default when the 2.4 exits beta
