### ISSUE TITLE
Symlink GBA_BIOS to BIOS Sambashare folder

### ISSUE THREAD

**Issue by stsfin** [petrockblog/RetroPie-Setup#577]
Symlink GBA_BIOS to BIOS Samba share folder, so it will be read from that folder and makes configuring the emulator easier. The GBA bios wont be read form that folder with out the symlink, this could be a feature on the RetroPie-Setup script "create bios symlinks for bios files available"

**Comment by joolswills** [comment]
This has been done. Also many more configs are now stored in /opt/retropie/configs - so you don't have to look around in the home directory etc.
