### ISSUE TITLE
changed gitPullOrClone function

### ISSUE THREAD

**Issue by joolswills** [petrockblog/RetroPie-Setup#590]
Just a heads up for @petrockblog and @gizmo98 regarding this function

see

https://github.com/petrockblog/RetroPie-Setup/commit/c3aa86b2ec36b318a3cc947dae19be519b25f6f2

NS parameter was only used for google code (as it couldn't do shallow clones). Made it automatic instead. It now takes an optional branch parameter instead which is more useful.

**Comment by petrockblog** [comment]
that is fine for me.
