### ISSUE TITLE
uae4all-rpi black screen?

### ISSUE THREAD

**Issue by shad00m** [petrockblog/RetroPie-Setup#601]
Hey, I tried using uae4all-rpi from "chips"  (http://www.raspberrypi.org/forums/viewtopic.php?f=35&t=17928) because the performance of the included uae4all seems to be pretty bad. In hope of having a better performance I tried the above mentioned version.
Sadly I only get a blackscreen with the 3 status boxes on the bottom, after that I have to reboot the rpi as I cannot exit anymore.

Is it even worth continuing or is the performance equally bad or is there simpy no "good" way of emulating amiga games on the pi?

Oh and the kick.rom works on uae4all so it shouldn't be that.

**Comment by joolswills** [comment]
no idea but that emulator is not part of retropie (yet) so you would do better to seek help on the forum thread.

I have no yet spent much time on the amiga emulators for retropie, but it is on my todo list.
