### ISSUE TITLE
Improve startAmigaDisk.sh

### ISSUE THREAD

**Issue by BrianGilbert** [petrockblog/RetroPie-Setup#612]
This allows loading 2 disk games from the menu by selecting the 1st disk it will symling df1.adf as well if the file name ends in disk1.adf or disk2.adf
```
#!/bin/bash

file="$1"
i=$((${#file}-4))
[[ -z "$file" ]] && exit 1

pushd "/opt/retropie/emulators/uae4all"
rm -fr df*.adf
case $file in
  *disk1.adf|*disk1.ADF)
    ln -s "$file" df0.adf
    ln -s "${file:0:-5}2${file:$i}" df1.adf
    ;;
  *disk2.adf|*disk2.ADF)
    ln -s "$file" df1.adf
    ln -s "${file:0:-5}1${file:$i}" df0.adf
    ;;
  *)
    ln -s "$file" df0.adf
    ;;
esac
/opt/retropie/supplementary/runcommand/runcommand.sh 1 ./uae4all "uae4all"
popd
```

**Comment by BrianGilbert** [comment]
possibly superceded by https://github.com/petrockblog/RetroPie-Setup/pull/560

**Comment by joolswills** [comment]
Going to close this if that's ok - just because the new emulator doesn't support loading from commandline (yet). if/when we add it, it may be enough just to insert the first disk, and others can be done from the gui. 

Thanks.
