### ISSUE TITLE
Famicom Disk System

### ISSUE THREAD

**Issue by KitchUK** [petrockblog/RetroPie-Setup#621]
I noticed from another post on the official Pi forums that the nestopia libretro core can run FDS games. Could you add this to Retropie? 

https://github.com/rdanbrook/nestopia/tree/master/libretro

**Comment by sycophantic** [comment]
I agree please add.

**Comment by justinbeaird** [comment]
Yes please!

**Comment by gizmo98** [comment]
It is there now. Please test it.

**Comment by DrMaxwell** [comment]
How do you switch disk sides?
