### ISSUE TITLE
Background sound emulationstation

### ISSUE THREAD

**Issue by expandables2** [petrockblog/RetroPie-Setup#624]
Hi is there a way i can add background sound to emulationstation version 1? I see it has scroll sound and select sound is there a way i can edit the code to have background sound? I am using retropie version 1

**Comment by expandables2** [comment]
Any reply please

**Comment by ProxyCell** [comment]
hi expandables2 - i'm not sure really, this isn't the Emulation Station repository :)
please head on over to: https://github.com/Aloshi/EmulationStation

**Comment by joolswills** [comment]
I don't think it supports background sound, and the 1.x version isn't developed I think. for emulationstation 2.x I would ask over at their forum as mentioned. thanks.

**Comment by expandables2** [comment]
I am asking how can i be able to develop version 1 of emulation station to have background sound. Since it is open source it should be able to am guessing.
