### ISSUE TITLE
QtSixA RPI2 compatibility

### ISSUE THREAD

**Issue by gizmo98** [petrockblog/RetroPie-Setup#642]
-mcpu=cortex-a7 needs gcc-4.7 or higher. Our PS3 controller module uses gcc 4.6: https://github.com/petrockblog/RetroPie-Setup/blob/master/scriptmodules/supplementary/ps3controller.sh#L19

Some users already had problems with __platform=rpi2: http://blog.petrockblock.com/forums/topic/raspberry-pi-2-compatibility/

gcc-4.7/4.8 compatibility must be tested.

**Comment by joolswills** [comment]
Already fixed - https://github.com/petrockblog/RetroPie-Setup/commit/88a6dfb60ecf4b393985043cb2bba20ee05df11b :)

**Comment by gizmo98** [comment]
Ohh good :+1:
