### ISSUE TITLE
Retroarch video driver gl is broken

### ISSUE THREAD

**Issue by gizmo98** [petrockblog/RetroPie-Setup#643]
I tried to build retroarch + pocketsnes + mupen64plus-libretro today with target rpi1 and rpi2. There is always a segfault if i try to start a game. If i use ”sdl2” or ”vg” video driver (retroarch.cfg) pocketsnes is useable. The rertoarch gl driver seems to have a bug ”atm”.

Some users also report alsa_thread errors.

**Comment by gizmo98** [comment]
Just recompiled everything today. GL driver is working again.

**Comment by joolswills** [comment]
glad it's sorted. thanks.
