### ISSUE TITLE
FUSE questions

### ISSUE THREAD

**Issue by space-invader** [petrockblog/RetroPie-Setup#662]
Hi.

I want to know if it is posible to start the spectrum games directly from the front end, what kind of file must be used and if it is posible to make a keyboard mapping as in DOSBox.

Sorry for my bad English.

Thanks in advance!

**Comment by joolswills** [comment]
this should be fixed. if you update your retropie-setup script and then run

```
sudo ./retropie_packages fuse configure
```

it should fix up the emulationstation config

**Comment by joolswills** [comment]
in regards to mapping you need to check the fuse documentation. I will be updating the retropie version of fuse soon.

**Comment by space-invader** [comment]
OK, I will try it.

Thanks!

**Comment by joolswills** [comment]
the fuse emulator has just been updated, so if you use option 5 in retropie-setup menu, you can install the latest version.
