### ISSUE TITLE
RPI2: Build using all available cores

### ISSUE THREAD

**Issue by sreichholf** [petrockblog/RetroPie-Setup#663]
Currently on the rpi 2 only 1 core is used to compile the sources.
I guess it would be a nice speedup on the RPI2 when compiling with

make -j\`nproc\` ....

This will launch up to "number-of-cores"-instances of make to speedup compiling.

**Comment by joolswills** [comment]
this is already supported but must be enabled manually. pass MAKEFLAGS="-jX"  to the script. 

```
sudo MAKEFLAGS="-j4" ./retropie-setup.sh

**Comment by joolswills** [comment]
note: some emulators may not build out of the box box when compiling in parallel. I think I've fixed most of them now, but some may still fail.

**Comment by sreichholf** [comment]
Ah, missed that option, thx for the info!

**Comment by joolswills** [comment]
it may be enabled by default in the future once we are 100% sure everything is completely working - and admittedly it isn't really documented yet - no-one likes writing documentation :)

**Comment by sreichholf** [comment]
Knowing about the option is fine for me ;). Everyone else has to start reading issues.
And you're right, no one likes that :D
