### ISSUE TITLE
Add wget to installer packages

### ISSUE THREAD

**Issue by redeye86** [petrockblog/RetroPie-Setup#672]
Hi,
i am using osmc (raspbian based) on a raspi 2 and i try to install retropie on it. It seems to work fine so far but in the installer logs i can see that some packages can not be installed because they do not exist. The reason is that wget is not installed by default.

Could you add wget to prerequisite packages in retropie_packages.sh (line 61)?

**Comment by m33x** [comment]
This was done 7 minutes ago. Can be marked as resolved.

**Comment by joolswills** [comment]
beat me to it - I meant to reference this ticket in the commit. oh well. anyway, the change is done - please let me know if there are any other needed packages.missing packages.
