### ISSUE TITLE
Manual patch description to remove mouse cursor in AdvMame:

### ISSUE THREAD

**Issue by andrewsil1** [petrockblog/RetroPie-Setup#674]
Since the AdvMame source isn't actually part of this repo, I'll just provide the appropriate chunk of code... Verified working with current 0.94 source from the setup script in tmp/build.

In advmame/advance/sdl/vsdl.c:
```c
 switch (sdl_state.cursor) {
        case adv_cursor_auto :
                /* if ((sdl_state.surface->flags & SDL_FULLSCREEN) != 0) { // Added block comment here
                        SDL_ShowCursor(SDL_DISABLE);
                } else {
                        SDL_ShowCursor(SDL_ENABLE);
                } */  //Ended here
                SDL_ShowCursor(SDL_DISABLE); // Added this line.
                break;
        case adv_cursor_on :
/*              SDL_ShowCursor(SDL_ENABLE); //Added block comment here.
                break; */ //Ended here so that both on/off cases disable the cursor.
        case adv_cursor_off :
                SDL_ShowCursor(SDL_DISABLE);
                break;

**Comment by joolswills** [comment]
in ~/.advance/advmame.rc what happens if you set "device_video_cursor" to off. That turns off the cursor for me without any code changes.

**Comment by andrewsil1** [comment]
Ugh, you're totally right!  Don't know why I didn't see that sooner.  Thanks for the suggestion, no patch needed.

**Comment by joolswills** [comment]
I will change the default config to include this. Cheers.

**Comment by andrewsil1** [comment]
Cheers to you- thanks for all the hard work.

_____________
Andy




On Sat, Feb 21, 2015 at 6:19 PM -0800, "Jools Wills" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will change the default config to include this. Cheers.

-
