### ISSUE TITLE
Add CPS1/2/3 games to ES

### ISSUE THREAD

**Issue by Elitius** [petrockblog/RetroPie-Setup#675]
Hi,

It would be great if you add CPS platform on Emustation and in rom folders. Roms works great with MAME, so why not add them ?

Thanks

**Comment by joolswills** [comment]
fbapi / fba-libretro) play negoeo and cps 1/2 games.

**Comment by Elitius** [comment]
I know, but Its possible to have a different menu for CPS with its own logo ?

**Comment by joolswills** [comment]
you could modify the fba logo to be CPS and call it that if you like, and then just launch cps/12 roms from there.

**Comment by Elitius** [comment]
It considered as a platform on GameDB, so I made some modifications in es_systems.cfg and added a skin. I'll commit it later.
