### ISSUE TITLE
can we add a perment fix to the retrobit atari sega usb adapter 

### ISSUE THREAD

**Issue by ehpower2** [petrockblog/RetroPie-Setup#676]
like stated above for the next update can we add a permanent fix to the image to handle that pesky adapter. I am unable to fix it this time using the provided information link

https://github.com/robmcmullen/hid-atari-retrobit

**Comment by joolswills** [comment]
Unfortunately I don't have any of the adapters - so we need someone who has one of them to contribute a fix really.

**Comment by petrockblog** [comment]
Sorry, I do not see how this project could fix the driver for that adapter. I suggest that you post an issue at their Github issues list.
