### ISSUE TITLE
Terminal prompt

### ISSUE THREAD

**Issue by expandables2** [petrockblog/RetroPie-Setup#681]
Hi what script initiates this when i log into the terminal.

 Monday, 23 February 2015,  4:15:32 pm UTC
  '. \ ' ' / .'   Linux 3.18.5+ armv6l GNU/Linux
   .~ .~~~..~.
  : .~.'~'.~. :   Filesystem      Size  Used Avail Use% Mounted on
 ~ (   ) (   ) ~  rootfs          1.8G  1.6G   63M  97% /
( : '~'.~.'~' : ) Uptime.............: 0 days, 00h11m34s
 ~ .~       ~. ~  Memory.............: 138900kB (Free) / 250868kB (Total)
  (   |   |   )   Running Processes..: 79
  '~         ~'   IP Address.........: 
    *--~-~--*     Temperature........: CPU: 45°C/113°F GPU: 45°C/113°F
                  The RetroPie Project, www.petrockblock.com

**Comment by joolswills** [comment]
it is at the end of ~/.bashrc

Please use the forum at http://blog.petrockblock.com/forums/forum/retropie-project-forum/ for general support requests. thanks.
