### ISSUE TITLE
Add Dreamcast emulator

### ISSUE THREAD

**Issue by Elitius** [petrockblog/RetroPie-Setup#689]
This emulator seems working on Rpi2 since few days:
https://github.com/reicast/reicast-emulator/tree/skmp/rapi2

According to this topic some games working, so why not include it in Retropie?
http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=100076

**Comment by joolswills** [comment]
on the thread I have read there is currently no sound.

Might be one for the experimental section perhaps when someone has time to implement it.

**Comment by Elitius** [comment]
I'll try to add it to Retropie next week and I let you know ;)

**Comment by joolswills** [comment]
thanks.
