### ISSUE TITLE
Building of picodrive fails

### ISSUE THREAD

**Issue by smoky19x** [petrockblog/RetroPie-Setup#699]
Hello,

if i try to install picodrive from source on a rpi2, it fails at the moment with the following error from the log:

"
...
In file included from platform/libretro/libretro.c:27:0:
./pico/pico_int.h:43:36: fatal error: ../cpu/cyclone/Cyclone.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'platform/libretro/libretro.o' failed
make: *** [platform/libretro/libretro.o] Error 1
/home/pi/RetroPie-Setup
Could not successfully build_picodrive Genesis LibretroCore Picodrive (/home/pi/RetroPie-Setup/tmp/build/picodrive/picodrive_libretro.so not found).
"

Maybe this can be fixed.

Regards,
Daniel

**Comment by joolswills** [comment]
please can you give me the complete log from the point of getting the sources etc.

**Comment by smoky19x** [comment]
OK, here it is:

/home/pi/RetroPie-Setup/tmp/build/picodrive /home/pi/RetroPie-Setup

= = = = = = = = = = = = = = = = = = = = =
Getting sources for Genesis LibretroCore Picodrive
= = = = = = = = = = = = = = = = = = = = =

picodrive-master/.gitignore
picodrive-master/.gitmodules
picodrive-master/AUTHORS
picodrive-master/COPYING
picodrive-master/ChangeLog
picodrive-master/Makefile
picodrive-master/Makefile.libretro
picodrive-master/README
picodrive-master/configure
picodrive-master/cpu/
picodrive-master/cpu/DrZ80/
picodrive-master/cpu/DrZ80/DrZ80.txt
picodrive-master/cpu/DrZ80/drz80.h
picodrive-master/cpu/DrZ80/drz80.s
picodrive-master/cpu/cyclone/
picodrive-master/cpu/cyclone_config.h
picodrive-master/cpu/cz80/
picodrive-master/cpu/cz80/cz80.c
picodrive-master/cpu/cz80/cz80.h
picodrive-master/cpu/cz80/cz80_op.c
picodrive-master/cpu/cz80/cz80_opCB.c
picodrive-master/cpu/cz80/cz80_opED.c
picodrive-master/cpu/cz80/cz80_opXY.c
picodrive-master/cpu/cz80/cz80_opXYCB.c
picodrive-master/cpu/cz80/cz80jmp.c
picodrive-master/cpu/cz80/cz80macro.h
picodrive-master/cpu/debug.c
picodrive-master/cpu/debug.h
picodrive-master/cpu/debug_net.c
picodrive-master/cpu/debug_net.h
picodrive-master/cpu/drc/
picodrive-master/cpu/drc/cmn.c
picodrive-master/cpu/drc/cmn.h
picodrive-master/cpu/drc/emit_arm.c
picodrive-master/cpu/drc/emit_x86.c
picodrive-master/cpu/fame/
picodrive-master/cpu/fame/fame.h
picodrive-master/cpu/fame/famec.c
picodrive-master/cpu/fame/famec_opcodes.h
picodrive-master/cpu/musashi/
picodrive-master/cpu/musashi/Makefile
picodrive-master/cpu/musashi/m68k.h
picodrive-master/cpu/musashi/m68k_in.c
picodrive-master/cpu/musashi/m68kconf.h
picodrive-master/cpu/musashi/m68kcpu.c
picodrive-master/cpu/musashi/m68kcpu.h
picodrive-master/cpu/musashi/m68kdasm.c
picodrive-master/cpu/musashi/m68kmake.c
picodrive-master/cpu/musashi/readme.txt
picodrive-master/cpu/sh2/
picodrive-master/cpu/sh2/compiler.c
picodrive-master/cpu/sh2/compiler.h
picodrive-master/cpu/sh2/mame/
picodrive-master/cpu/sh2/mame/sh2.c
picodrive-master/cpu/sh2/mame/sh2dasm.c
picodrive-master/cpu/sh2/mame/sh2dasm.h
picodrive-master/cpu/sh2/mame/sh2pico.c
picodrive-master/cpu/sh2/sh2.c
picodrive-master/cpu/sh2/sh2.h
picodrive-master/jni/
picodrive-master/jni/Android.mk
picodrive-master/jni/Application.mk
picodrive-master/pico/
picodrive-master/pico/32x/
picodrive-master/pico/32x/32x.c
picodrive-master/pico/32x/32x_draw.c
picodrive-master/pico/32x/32x_memory.c
picodrive-master/pico/32x/draw_arm.s
picodrive-master/pico/32x/pwm.c
picodrive-master/pico/32x/sh2soc.c
picodrive-master/pico/arm_features.h
picodrive-master/pico/cart.c
picodrive-master/pico/carthw.cfg
picodrive-master/pico/carthw/
picodrive-master/pico/carthw/carthw.c
picodrive-master/pico/carthw/carthw.h
picodrive-master/pico/carthw/svp/
picodrive-master/pico/carthw/svp/compiler.c
picodrive-master/pico/carthw/svp/compiler.h
picodrive-master/pico/carthw/svp/imageformat.txt
picodrive-master/pico/carthw/svp/ssp16.c
picodrive-master/pico/carthw/svp/ssp16.h
picodrive-master/pico/carthw/svp/stub_arm.S
picodrive-master/pico/carthw/svp/svp.c
picodrive-master/pico/carthw/svp/svp_memory.c
picodrive-master/pico/carthw_cfg.c
picodrive-master/pico/cd/
picodrive-master/pico/cd/cd_image.c
picodrive-master/pico/cd/cd_memory.c
picodrive-master/pico/cd/cd_misc.c
picodrive-master/pico/cd/cd_sek.c
picodrive-master/pico/cd/cdc.c
picodrive-master/pico/cd/cdd.c
picodrive-master/pico/cd/cdd.h
picodrive-master/pico/cd/cell_map.c
picodrive-master/pico/cd/cue.c
picodrive-master/pico/cd/cue.h
picodrive-master/pico/cd/genplus_macros.h
picodrive-master/pico/cd/gfx.c
picodrive-master/pico/cd/gfx_dma.c
picodrive-master/pico/cd/mcd.c
picodrive-master/pico/cd/mcd_arm.s
picodrive-master/pico/cd/memory_arm.s
picodrive-master/pico/cd/misc_arm.s
picodrive-master/pico/cd/pcm.c
picodrive-master/pico/debug.c
picodrive-master/pico/debug.h
picodrive-master/pico/debugCPU.c
picodrive-master/pico/draw.c
picodrive-master/pico/draw2.c
picodrive-master/pico/draw2_arm.S
picodrive-master/pico/draw_amips.s
picodrive-master/pico/draw_arm.S
picodrive-master/pico/eeprom.c
picodrive-master/pico/m68kif_cyclone.s
picodrive-master/pico/media.c
picodrive-master/pico/memory.c
picodrive-master/pico/memory.h
picodrive-master/pico/memory_amips.s
picodrive-master/pico/memory_arm.s
picodrive-master/pico/misc.c
picodrive-master/pico/misc_amips.s
picodrive-master/pico/misc_arm.s
picodrive-master/pico/mode4.c
picodrive-master/pico/patch.c
picodrive-master/pico/patch.h
picodrive-master/pico/pico.c
picodrive-master/pico/pico.h
picodrive-master/pico/pico/
picodrive-master/pico/pico/pico_memory.c
picodrive-master/pico/pico/pico_pico.c
picodrive-master/pico/pico/xpcm.c
picodrive-master/pico/pico_cmn.c
picodrive-master/pico/pico_int.h
picodrive-master/pico/sek.c
picodrive-master/pico/sms.c
picodrive-master/pico/sound/
picodrive-master/pico/sound/mix.c
picodrive-master/pico/sound/mix.h
picodrive-master/pico/sound/mix_arm.s
picodrive-master/pico/sound/sn76496.c
picodrive-master/pico/sound/sn76496.h
picodrive-master/pico/sound/sound.c
picodrive-master/pico/sound/ym2612.c
picodrive-master/pico/sound/ym2612.h
picodrive-master/pico/sound/ym2612_arm.s
picodrive-master/pico/state.c
picodrive-master/pico/state.h
picodrive-master/pico/videoport.c
picodrive-master/pico/z80if.c
picodrive-master/platform/
picodrive-master/platform/base_readme.txt
picodrive-master/platform/common/
picodrive-master/platform/common/arm_utils.h
picodrive-master/platform/common/arm_utils.s
picodrive-master/platform/common/common.mak
picodrive-master/platform/common/config_file.c
picodrive-master/platform/common/config_file.h
picodrive-master/platform/common/emu.c
picodrive-master/platform/common/emu.h
picodrive-master/platform/common/input_pico.h
picodrive-master/platform/common/main.c
picodrive-master/platform/common/menu_pico.c
picodrive-master/platform/common/menu_pico.h
picodrive-master/platform/common/mp3.c
picodrive-master/platform/common/mp3.h
picodrive-master/platform/common/mp3_dummy.c
picodrive-master/platform/common/mp3_helix.c
picodrive-master/platform/common/mp3_libavcodec.c
picodrive-master/platform/common/plat_sdl.c
picodrive-master/platform/common/version.h
picodrive-master/platform/game_def.cfg
picodrive-master/platform/gizmondo/
picodrive-master/platform/gizmondo/Makefile
picodrive-master/platform/gizmondo/asm_utils.h
picodrive-master/platform/gizmondo/asm_utils.s
picodrive-master/platform/gizmondo/emu.c
picodrive-master/platform/gizmondo/emu.h
picodrive-master/platform/gizmondo/giz.c
picodrive-master/platform/gizmondo/giz.h
picodrive-master/platform/gizmondo/main.c
picodrive-master/platform/gizmondo/menu.c
picodrive-master/platform/gizmondo/menu.h
picodrive-master/platform/gp2x/
picodrive-master/platform/gp2x/940ctl.c
picodrive-master/platform/gp2x/940ctl.h
picodrive-master/platform/gp2x/Makefile
picodrive-master/platform/gp2x/PicoDrive.gpe
picodrive-master/platform/gp2x/PicoDrive.ini
picodrive-master/platform/gp2x/PicoDrive.png
picodrive-master/platform/gp2x/PicoDrive_s.png
picodrive-master/platform/gp2x/PicoDrive_t.png
picodrive-master/platform/gp2x/code940/
picodrive-master/platform/gp2x/code940/940.c
picodrive-master/platform/gp2x/code940/940init.s
picodrive-master/platform/gp2x/code940/940shared.h
picodrive-master/platform/gp2x/code940/Makefile
picodrive-master/platform/gp2x/code940/memcpy.s
picodrive-master/platform/gp2x/code940/mp3test.c
picodrive-master/platform/gp2x/code940/uClibc/
picodrive-master/platform/gp2x/code940/uClibc/README
picodrive-master/platform/gp2x/code940/uClibc/e_log.c
picodrive-master/platform/gp2x/code940/uClibc/e_pow.c
picodrive-master/platform/gp2x/code940/uClibc/e_rem_pio2.c
picodrive-master/platform/gp2x/code940/uClibc/e_sqrt.c
picodrive-master/platform/gp2x/code940/uClibc/k_cos.c
picodrive-master/platform/gp2x/code940/uClibc/k_rem_pio2.c
picodrive-master/platform/gp2x/code940/uClibc/k_sin.c
picodrive-master/platform/gp2x/code940/uClibc/math.h
picodrive-master/platform/gp2x/code940/uClibc/math_private.h
picodrive-master/platform/gp2x/code940/uClibc/memset.s
picodrive-master/platform/gp2x/code940/uClibc/s_copysign.c
picodrive-master/platform/gp2x/code940/uClibc/s_fabs.c
picodrive-master/platform/gp2x/code940/uClibc/s_floor.c
picodrive-master/platform/gp2x/code940/uClibc/s_scalbn.c
picodrive-master/platform/gp2x/code940/uClibc/s_sin.c
picodrive-master/platform/gp2x/code940/uClibc/wrappers.c
picodrive-master/platform/gp2x/emu.c
picodrive-master/platform/gp2x/menu.c
picodrive-master/platform/gp2x/plat.c
picodrive-master/platform/gp2x/plat.h
picodrive-master/platform/gp2x/skin/
picodrive-master/platform/gp2x/skin/background.png
picodrive-master/platform/gp2x/skin/font.png
picodrive-master/platform/gp2x/skin/readme.txt
picodrive-master/platform/gp2x/skin/selector.png
picodrive-master/platform/gp2x/skin/skin.txt
picodrive-master/platform/gp2x/test.c
picodrive-master/platform/gp2x/vid_mmsp2.c
picodrive-master/platform/gp2x/vid_pollux.c
picodrive-master/platform/gp2x/warm.c
picodrive-master/platform/gp2x/warm.h
picodrive-master/platform/libpicofe/
picodrive-master/platform/libretro/
picodrive-master/platform/libretro/libretro.c
picodrive-master/platform/libretro/libretro.h
picodrive-master/platform/libretro/msvc/
picodrive-master/platform/libretro/msvc/msvc-2003-xbox1.bat
picodrive-master/platform/libretro/msvc/msvc-2010-360.bat
picodrive-master/platform/libretro/msvc/msvc-2010.bat
picodrive-master/platform/libretro/msvc/msvc-2010.sln
picodrive-master/platform/libretro/msvc/msvc-2010/
picodrive-master/platform/libretro/msvc/msvc-2010/libretro.def
picodrive-master/platform/libretro/msvc/msvc-2010/msvc-2010.suo
picodrive-master/platform/libretro/msvc/msvc-2010/msvc-2010.vcxproj
picodrive-master/platform/libretro/msvc/msvc-2010/msvc-2010.vcxproj.filters
picodrive-master/platform/linux/
picodrive-master/platform/linux/README
picodrive-master/platform/linux/blit.c
picodrive-master/platform/linux/emu.c
picodrive-master/platform/linux/in_evdev.h
picodrive-master/platform/linux/io.c
picodrive-master/platform/linux/log_io.c
picodrive-master/platform/linux/log_io.h
picodrive-master/platform/linux/pprof.c
picodrive-master/platform/linux/pprof.h
picodrive-master/platform/opendingux/
picodrive-master/platform/opendingux/data/
picodrive-master/platform/opendingux/data/default.gcw0.desktop
picodrive-master/platform/opendingux/data/megadrive.png
picodrive-master/platform/opendingux/data/skin/
picodrive-master/platform/opendingux/data/skin/background.png
picodrive-master/platform/opendingux/data/skin/font.png
picodrive-master/platform/opendingux/data/skin/readme.txt
picodrive-master/platform/opendingux/data/skin/skin.txt
picodrive-master/platform/opendingux/inputmap.c
picodrive-master/platform/pandora/
picodrive-master/platform/pandora/Makefile
picodrive-master/platform/pandora/PicoDrive.png
picodrive-master/platform/pandora/PicoDrive.pxml.template
picodrive-master/platform/pandora/PicoDrive.sh
picodrive-master/platform/pandora/PicoDrive_p.png
picodrive-master/platform/pandora/asm_utils.h
picodrive-master/platform/pandora/asm_utils.s
picodrive-master/platform/pandora/make_pxml.sh
picodrive-master/platform/pandora/menu.c
picodrive-master/platform/pandora/picorestore.c
picodrive-master/platform/pandora/plat.c
picodrive-master/platform/pandora/plat.h
picodrive-master/platform/pandora/skin/
picodrive-master/platform/pandora/skin/background.png
picodrive-master/platform/pandora/skin/font.png
picodrive-master/platform/pandora/skin/readme.txt
picodrive-master/platform/pandora/skin/selector.png
picodrive-master/platform/pandora/skin/skin.txt
picodrive-master/platform/psp/
picodrive-master/platform/psp/Makefile
picodrive-master/platform/psp/asm_utils.h
picodrive-master/platform/psp/asm_utils.s
picodrive-master/platform/psp/data/
picodrive-master/platform/psp/data/bg32.bin
picodrive-master/platform/psp/data/bg40.bin
picodrive-master/platform/psp/data/icon.png
picodrive-master/platform/psp/emu.c
picodrive-master/platform/psp/emu.h
picodrive-master/platform/psp/main.c
picodrive-master/platform/psp/menu.c
picodrive-master/platform/psp/menu.h
picodrive-master/platform/psp/mp3.c
picodrive-master/platform/psp/mp3.h
picodrive-master/platform/psp/psp.c
picodrive-master/platform/psp/psp.h
picodrive-master/platform/psp/skin/
picodrive-master/platform/psp/skin/background.png
picodrive-master/platform/psp/skin/font.png
picodrive-master/platform/psp/skin/readme.txt
picodrive-master/platform/psp/skin/selector.png
picodrive-master/platform/psp/skin/skin.txt
picodrive-master/platform/win32/
picodrive-master/platform/win32/Makefile
picodrive-master/platform/win32/in_vk.c
picodrive-master/platform/win32/in_vk.h
picodrive-master/platform/win32/main.c
picodrive-master/platform/win32/main.h
picodrive-master/platform/win32/plat.c
picodrive-master/platform/win32/readme.txt
picodrive-master/tools/
picodrive-master/tools/Makefile
picodrive-master/tools/amalgamate.c
picodrive-master/tools/bin_to_cso_mp3/
picodrive-master/tools/bin_to_cso_mp3/bin_to_cso_mp3.c
picodrive-master/tools/bin_to_cso_mp3/bin_to_cso_mp3.exe
picodrive-master/tools/bin_to_cso_mp3/readme.txt
picodrive-master/tools/bselect.c
picodrive-master/tools/compdecomp.c
picodrive-master/tools/gcda.c
picodrive-master/tools/make_carthw_c.c
picodrive-master/tools/mkbgxx.c
picodrive-master/tools/mkt1.c
picodrive-master/tools/textfilter.c
picodrive-master/unzip/
picodrive-master/unzip/unzip.c
picodrive-master/unzip/unzip.h
picodrive-master/unzip/unzip_stream.c
picodrive-master/unzip/unzip_stream.h
picodrive-master/zlib/
picodrive-master/zlib/ChangeLog
picodrive-master/zlib/Makefile
picodrive-master/zlib/Makefile.in
picodrive-master/zlib/README
picodrive-master/zlib/adler32.c
picodrive-master/zlib/compress.c
picodrive-master/zlib/crc32.c
picodrive-master/zlib/crc32.h
picodrive-master/zlib/deflate.c
picodrive-master/zlib/deflate.h
picodrive-master/zlib/example.c
picodrive-master/zlib/gzio.c
picodrive-master/zlib/gzio_symb.c
picodrive-master/zlib/gzio_symb.h
picodrive-master/zlib/infback.c
picodrive-master/zlib/inffast.c
picodrive-master/zlib/inffast.h
picodrive-master/zlib/inffixed.h
picodrive-master/zlib/inflate.c
picodrive-master/zlib/inflate.h
picodrive-master/zlib/inftrees.c
picodrive-master/zlib/inftrees.h
picodrive-master/zlib/trees.c
picodrive-master/zlib/trees.h
picodrive-master/zlib/uncompr.c
picodrive-master/zlib/zconf.h
picodrive-master/zlib/zlib.h
picodrive-master/zlib/zutil.c
picodrive-master/zlib/zutil.h
You need to run this command from the toplevel of the working tree.
You need to run this command from the toplevel of the working tree.
/home/pi/RetroPie-Setup
/home/pi/RetroPie-Setup/tmp/build/picodrive /home/pi/RetroPie-Setup

= = = = = = = = = = = = = = = = = = = = =
Building Genesis LibretroCore Picodrive
= = = = = = = = = = = = = = = = = = = = =

rm -f PicoDrive platform/common/mp3.o platform/common/mp3_dummy.o zlib/gzio.o zlib/inffast.o zlib/inflate.o zlib/inftrees.o zlib/trees.o zlib/deflate.o zlib/crc32.o zlib/adler32.o zlib/zutil.o zlib/compress.o zlib/uncompr.o unzip/unzip.o unzip/unzip_stream.o pico/pico.o pico/cart.o pico/memory.o pico/state.o pico/sek.o pico/z80if.o pico/videoport.o pico/draw2.o pico/draw.o pico/mode4.o pico/misc.o pico/eeprom.o pico/patch.o pico/debug.o pico/media.o pico/sms.o pico/cd/mcd.o pico/cd/cd_memory.o pico/cd/cd_sek.o pico/cd/cdc.o pico/cd/cdd.o pico/cd/cd_image.o pico/cd/cue.o pico/cd/gfx.o pico/cd/gfx_dma.o pico/cd/cd_misc.o pico/cd/pcm.o pico/32x/32x.o pico/32x/32x_memory.o pico/32x/32x_draw.o pico/32x/sh2soc.o pico/32x/pwm.o pico/pico/pico_pico.o pico/pico/pico_memory.o pico/pico/xpcm.o pico/carthw/carthw.o pico/carthw/svp/svp.o pico/carthw/svp/svp_memory.o pico/carthw/svp/ssp16.o pico/sound/sound.o pico/sound/sn76496.o pico/sound/ym2612.o pico/sound/mix.o cpu/fame/famec.o cpu/cz80/cz80.o cpu/drc/cmn.o cpu/sh2/sh2.o cpu/sh2/mame/sh2pico.o
rm -f -r .opk_data
cc -O2 -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -pipe -marm -DNO_ZLIB -fPIC -Wall -ggdb -falign-functions=2 -I. -DINLINE=inline -O2 -DNDEBUG -ffunction-sections -D_SVP_DRC -DEMU_C68K -D_USE_DRZ80 -DDRC_SH2   -c -o platform/libretro/libretro.o platform/libretro/libretro.c
In file included from platform/libretro/libretro.c:27:0:
./pico/pico_int.h:43:36: fatal error: ../cpu/cyclone/Cyclone.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'platform/libretro/libretro.o' failed
make: *** [platform/libretro/libretro.o] Error 1
/home/pi/RetroPie-Setup
Could not successfully build_picodrive Genesis LibretroCore Picodrive (/home/pi/RetroPie-Setup/tmp/build/picodrive/picodrive_libretro.so not found).

**Comment by joolswills** [comment]
ok thanks. and you are building this directly on the pi2 and not in a chroot environment ?

If so, it looks like the code to detect a chroot environment isn't working and being triggered which it shouldn't (we have code to download data differently in an emulated chroot environment, which doesn't work with picodrive).

I may have to change the code to sort this - could you detail your set up ? are you using the image or installing on raspbian. I'd be interested in a copy of your image to see why it thinks you are in a chroot.

**Comment by smoky19x** [comment]
Sorry, you are right. It was build in a chroot environment with an image of the sdcard version. I did not know that it makes such a difference.

Could you please explain in short why it is a difference for compiling if it is made in a chroot environment?

**Comment by joolswills** [comment]
aah - always good to mention details like this :) 

I do most of the development in an emulated chroot, so it handles this sirtuation, including setting the emulated arm cpu etc depending if building for rpi1 or rpi2.

unfortunately though, some stuff can lock up in this environment and git seems to do this often (and cmake https://bugs.launchpad.net/qemu/+bug/955379). so to avoid this, instead of using git, to download from github a tar is downloaded if in a chroot environment. this doesn't work with picodrive though  as it uses git submodules for the cyclone emulator.

to force the code to use git you can edit scriptmodules/helpers.sh and comment out the code in function gitPullOrClone that uses tar. At some point I need to do an exclusion for picodrive for this (the only emulator currently affected)
