### ISSUE TITLE
Add themes for lynx, vectrex, esconfig/configuration 

### ISSUE THREAD

**Issue by gizmo98** [petrockblog/RetroPie-Setup#701]
Themes for the named systems are missing. The simple theme should be modified. There should be also one default theme for unknown systems.

**Comment by nilsbyte** [comment]
Hi gizmo, thanks. I have already added these to my TODO list. You can visit the thrad for the stock theme in the official ES forum here: http://emulationstation.org/forum/index.php?topic=35.0

I will close this because it's not really an issue, more of a feature request, and not for ES itself :)

**Comment by gizmo98** [comment]
Ok. Then i will close this pr now. Please add a blank system with a empty logo for new systems as well. Thank you.

**Comment by nilsbyte** [comment]
v1.4 is out, includes the named themes :) grab at http://blog.nilsbyte.de/ :)
