### ISSUE TITLE
wording in main menu

### ISSUE THREAD

**Issue by joolswills** [petrockblog/RetroPie-Setup#704]
I would like to tweak the wording in the main retropie-setup menu, and perhaps add an additional dialog screen before the source install. Currently it tempts people to do the source build, which of course can have problems (such as retroarch has been broken for a few days). 

When things go wrong, it can be tricky to help if users are not familiar with the linux console. As our binaries are now split, and can be quite quickly updated as needed, I think we should put more emphasis of users to use the binary install, or if they choose the source install, mention that they should be prepared to deal with any issues that arise, and may need to use the linux commandline etc.

What do you think @petrockblog ?

**Comment by petrockblog** [comment]
Good idea. The current menu (texts as well as the structure) has not seen much development for some time.
