### ISSUE TITLE
Can we add reicast emulator to retropie?

### ISSUE THREAD

**Issue by jwkassem** [petrockblog/RetroPie-Setup#706]
I noticed some chatter on rpi forums about reicast. looks promising for the rpi2. has its own rpi branch / fork. hopefully it gets some attention. 

https://github.com/reicast/reicast-emul ... skmp/rapi2
http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=100076

**Comment by joolswills** [comment]
aah right. that emulator. there is already a ticket for that - https://github.com/petrockblog/RetroPie-Setup/issues/689

**Comment by jwkassem** [comment]
ah great you guys are on the ball. fantastic project. kudos to all involved here.
