### ISSUE TITLE
cave story segfaults on launch (Rpi 2)

### ISSUE THREAD

**Issue by cacophony555** [petrockblog/RetroPie-Setup#708]
I have the 2.6 image running on my RP 2, and used retropie_setup.sh to install the cave story core. But when I try to launch it from emulationstation it immediately causes a segmentation fault and quits back to emulationstation. 

I can try to get more logging info for you if needed, but I'm hoping it's easily reproducible and not needed given that I'm basically using an off the shelf 2.6 image.

**Comment by joolswills** [comment]
did you install the datafiles ? we don't ship with them now - as it's against the authors wishes. You need /opt/retropie/libretrocores/cavestory/datafiles/Doukutsu.exe

**Comment by joolswills** [comment]
(also it is in experimental section - and i've not tested it recently).

**Comment by cacophony555** [comment]
I had no idea I needed to install datafiles? Is this documented somewhere? Where can I get these files?

**Comment by joolswills** [comment]
It's not documented, and in the same way regarding copyrighted roms, I can't help with that I'm afraid apart from the info I've given - you need the cavestory datafiles in the location above.
