### ISSUE TITLE
optimization for multi-core pi2

### ISSUE THREAD

**Issue by ric96** [petrockblog/RetroPie-Setup#716]
Has the code been optimized to take the advantage of the quad core processor of the pi2 at both compilation and run time ?

**Comment by joolswills** [comment]
regarding compilation - see 

https://github.com/petrockblog/RetroPie-Setup/issues/663 and
https://github.com/petrockblog/RetroPie-Setup/issues/691

Some emulators have some simple multi core support such as a separate thread for rendering etc, but most emulators are single threaded. There is no magical way to make something like an emulator use multiple cores, and by design, it is difficult to emulate a system with multiple threads.

**Comment by ric96** [comment]
What about compilation of retropie?

**Comment by joolswills** [comment]
I just linked you to two previous tickets on the topic, both with the answer.

**Comment by ric96** [comment]
Oh yeh, thnx will try it out!!

**Comment by joolswills** [comment]
np.

**Comment by ric96** [comment]
Neogeo failed to build :(

**Comment by joolswills** [comment]
please post the build log (from logs/)

note that some emulators may fail to build with -jX - hence it is not switched on by default. Not all emulators have makefiles/dependencies that are compatible with parallel building.

**Comment by ric96** [comment]
Gamegear too failed

**Comment by ric96** [comment]
I'll post it once it's over,
I did want to log whatever fails on -j4 so that it can be fixed or maybe an exception could be added so that they are always built without -j4

**Comment by joolswills** [comment]
It's not always consistent, but that is already the plan - however I am busy on other things currently. Did you read the other threads regarding this as I went into some detail.

**Comment by ric96** [comment]
log: https://drive.google.com/file/d/0B4VR-WNTOX0qNm9abm5qd0kxYUU/view?usp=sharing

also on starting emulationstation it says:

**Comment by ric96** [comment]
https://drive.google.com/file/d/0B4VR-WNTOX0qQVRTdVpJQUdZNnc/view?usp=sharing

**Comment by gizmo98** [comment]
If i run emulationstation with sudo or as a different user i have the same message. But this is not the normal use case.

**Comment by ric96** [comment]
If I don't run with sudo it gives me permission denied error!!

**Comment by joolswills** [comment]
yeh from the log osmose/gngeo failed. this is usual. for those you can build without -jX for now.

**Comment by joolswills** [comment]
you get permissions denied as ~/.pi/.emulation station is now owned by root. you need to chown it. But just install from binaries and everything is simpler :)

**Comment by joolswills** [comment]
chown -R pi:pi ~/.emulationstation
