### ISSUE TITLE
Build time in log

### ISSUE THREAD

**Issue by ric96** [petrockblog/RetroPie-Setup#724]
The automated log created by the could do some good with a time log too.
like start, end and total time taken.

**Comment by joolswills** [comment]
Thanks. done.

**Comment by ric96** [comment]
Just shows the start time, not the end or total time taken. Although it does show time at Emulation Station Theme Simple which is pretty close to the end time.

**Comment by joolswills** [comment]
Fixed. It was worknig for binary install etc, but I had forgotten to move a line for the source. should be ok if you update. thanks.
