### ISSUE TITLE
Github organization "RetroPie"?

### ISSUE THREAD

**Issue by petrockblog** [petrockblog/RetroPie-Setup#725]
Do you think that we should open a Github organization "RetroPie"? Would we have any benefits? Or would we just create unnecessary overhead? I would need to change quite a few URLs and the new URL would not be so well known at the beginning.

@joolswills @gizmo98 What do you think?

**Comment by joolswills** [comment]
Could be useful to keep all the repositories in one place at least, but it's not absolutely required if you don't think it's needed. I'm not in any rush for it - far too much ongoing stuff currently to worry about updating urls :) but perhaps when/if things settle down.

**Comment by gizmo98** [comment]
A totally agree with jools. If there is less ongoing stuff we can think about "one" place for all retropie repos.

**Comment by petrockblog** [comment]
I have reserved retropie as organization at Github. We'll see, if we need this at some point on time ...

**Comment by joolswills** [comment]
I think it would be a good time to do this - are you happy to move this and the other related repositories to the organisation ? If you make me an admin I can do the same for my repositories (and gizmo can do for his etc).

**Comment by petrockblog** [comment]
Sure - I will do that tomorrow!

**Comment by joolswills** [comment]
cheers!

**Comment by joolswills** [comment]
*bump* :)

**Comment by petrockblog** [comment]
I have finally moved the repository to the organization. @joolswills and @gizmo98, I have send you two an invitation to become team members. Still have to figure out the best access rights settings, though.
