### ISSUE TITLE
libsdl2-dev dependency

### ISSUE THREAD

**Issue by ProxyCell** [petrockblog/RetroPie-Setup#739]
Please do a quick search through this repo for "libsdl2-dev" and you will find lots of references to it.
Unfortunately I can't seem to install this by just doing "apt-get install libsdl2-dev"
The package system is never able to locate it.

edit: it is also worth mentioning that when i tried to do a source build last night, it threw an error concerning this but continued on.

**Comment by joolswills** [comment]
it's not in raspbian - it is provided as part of retropie. The script automatically installs it as needed.

Not sure what issue you are referring to - please can you be more specific ?

**Comment by ProxyCell** [comment]
oh ok, i just started the gPSP GBA emulator source build and it began downloading it from the petrockblog website

i'm sorry, i thought it was a mistyped dependency there because the same emulator then downloaded libsdl1.2-dev

**Comment by joolswills** [comment]
gpsp uses sdl1.2-dev not sdl2-dev.

retropie includes custom sdl1.2 packages and sdl2 packages.

**Comment by joolswills** [comment]
(the reason being to fix up some issues with sdl1.2  that used to cause black screens, and also the inclusion of a single library that has a dispmanx backend also)
