### ISSUE TITLE
[Game request] Descent 1 & 2!

### ISSUE THREAD

**Issue by C-Fu** [petrockblog/RetroPie-Setup#742]
Somebody have ported/patched the open source version of Descent 1 & 2 for RPi (and RPi 2)!! 

And somebody else have kindly made a script to automate installation of the game on the latest posting on that thread.

http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=14108

I'm playing the game right now on RPi2, almost super smooth, getting 45-55fps on 1080p on max graphic settings :dancers:

**Comment by MattWatt** [comment]
Wow, that's really cool.  One of my favorite games growing up.  I'd love to try this on the Pi.

**Comment by kofronpi** [comment]
Amazing, I've got to try it !

**Comment by free5ty1e** [comment]
I've created a script to install Descent 1 and Descent 2 including the required shareware files.  At some point I want to learn how to turn it into a RetroPie script; in the meantime, if anyone is interested to try it out, here is the script:
https://github.com/free5ty1e/primestationone/blob/master/bin/installDescent1and2.sh

and here are the launch scripts to put in EmulationStation under PORTS:
https://github.com/free5ty1e/primestationone/blob/master/RetroPie/roms/ports/Descent1.sh
https://github.com/free5ty1e/primestationone/blob/master/RetroPie/roms/ports/Descent2.sh

Enjoy!

**Comment by taalas** [comment]
Looking forward to trying that. Thanks you!

**Comment by MattWatt** [comment]
This is now in the experimental install menu and can be closed.
