### ISSUE TITLE
retro_setup error install to my rpi raspbian

### ISSUE THREAD

**Issue by benjic78** [petrockblog/RetroPie-Setup#752]
sorry, my rpi language is in French:
When i execute #sudo ./retropie_setup.sh
Les paquets supplémentaires suivants seront installés :
  cpp-4.7 libstdc++6-4.7-dev
Paquets suggérés :
  gcc-4.7-locales gcc-4.7-doc libstdc++6-4.7-dbg libmudflap0-4.7-dev
  libgcc1-dbg libgomp1-dbg libitm1-dbg libquadmath-dbg libmudflap0-dbg
  libcloog-ppl0 libppl-c2 libppl7 libstdc++6-4.7-doc
Les NOUVEAUX paquets suivants seront installés :
  cpp-4.7 g++-4.7 gcc-4.7 libstdc++6-4.7-dev xmlstarlet
0 mis à jour, 5 nouvellement installés, 0 à enlever et 9 non mis à jour.
Il est nécessaire de prendre 17,2 Mo dans les archives.
Après cette opération, 46,9 Mo d'espace disque supplémentaires seront utilisés.
ATTENTION : les paquets suivants n'ont pas été authentifiés.
  cpp-4.7 gcc-4.7 libstdc++6-4.7-dev g++-4.7 xmlstarlet
E: Il y a des problèmes et -y a été employé sans --force-yes
Unable to install packages required by /home/pi/git/RetroPie-Setup/retropie_packages.sh
Could not install package(s): gcc-4.7
g++-4.7
xmlstarlet.
pi@raspberrypi ~/git/RetroPie-Setup $

I solved my problem with command : # sudo apt-get install --force-yes cpp-4.7 g++-4.7 gcc-4.7 libstdc++6-4.7-dev xmlstarlet

**Comment by joolswills** [comment]
You are missing the key for the repository - old raspbian or ? 

to add the key
```
wget http://archive.raspbian.org/raspbian.public.key -O - | sudo apt-key add -
````
