### ISSUE TITLE
updating emulation station gets stuck then crashes 

### ISSUE THREAD

**Issue by InsecureSpike** [petrockblog/RetroPie-Setup#755]
ok, i'm in the process of a clean install, via the current rpi2.img, but when i update emilationstation, from the set-up menus it gets stuck at 

[ 24%] Building CXX object es-core/CMakeFiles/es-core.dir/src/components/ImageComponent.cpp.o

and then nothing.... and the only way i can shut it down is to pull the power!!

any ideas?

**Comment by joolswills** [comment]
your pi crashed ? out of ram ? probably bit of both.

not a retropie bug though - you might want to check free ram / decrease amount allocated to gpu.

but the binaries are up to date, so no need to build from source.

**Comment by InsecureSpike** [comment]
ram set at 256

**Comment by joolswills** [comment]
I would allocate less to the gpu if building from source - no idea what pi you have though, so little to go on.

**Comment by joolswills** [comment]
i see you said rpi2 image, so I assume a rpi 2 ? so you have allocated 256mb to the gpu ?

should be enough to build emulation station, but it takes a while. overclocked ? decent psu / cable ?

The best fix is to install from binary - but the problem is related to your setup/rather than a retropie issue imho.

**Comment by joolswills** [comment]
you can also try

```sudo MAKEFLAGS="-j1" ./retropie_setup.sh

**Comment by InsecureSpike** [comment]
ok, i'll try some things out, and then get back,
thanks mate

**Comment by InsecureSpike** [comment]
ok think i figured it out, i've been dong this..

http://www.htpcguides.com/power-2-5-hard-drive-with-raspberry-pi-b/

but this time i skipped the "Now update the Raspberry Pi’s firmware"
and just did the /boot/config.txt edit, and all seams good so far..

just doing a binaries update now

**Comment by joolswills** [comment]
it would have been useful if you had mentioned you had a 2.5 disk plugged in. Glad you have it sorted.
