### ISSUE TITLE
Configure Audio Settings - ambiguous redirect

### ISSUE THREAD

**Issue by cincospenguinos** [petrockblog/RetroPie-Setup#761]
I just pulled the most recent RetroPie-Setup script and attempted to configure my audio settings. Running it gives me the following error:

```BASH
/home/pi/RetroPie-Setup/scriptmodules/admin/setup.sh: line 203: $logfilename: ambiguous redirect
date: invalid date '@'
Log started at:
```

I imagine it's a pretty recent bug, as it's never done this before.

**Comment by oxivanisher** [comment]
The same thing happens on my Pi if i try to install additional packages like Minecraft or Darkplaces.

**Comment by joolswills** [comment]
apologies. my fault. fixing it now.

**Comment by joolswills** [comment]
please update and it should be sorted.

**Comment by oxivanisher** [comment]
Perfect! My problems are solved with this :+1:
