### ISSUE TITLE
retroarch assets

### ISSUE THREAD

**Issue by joolswills** [petrockblog/RetroPie-Setup#762]
@gizmo98 are the RetroArch assets currenty used for anything ? Do we use any of the theme /graphic data for "lakka" ?

**Comment by gizmo98** [comment]
Not yet. I tried to use them in RGUI but had no luck and i have not done a closer look until now.

**Comment by joolswills** [comment]
If possible it would be good to strip this down a bit. the assets add 23M of additional stuff to retroarch, and the overlays add a fair bit too. ideally we would only install stuff that we can use (eg, we wouldn't need any original xcf image files I guess and so on)

**Comment by joolswills** [comment]
thanks
