### ISSUE TITLE
Enhancement: Add RPI-Update to Retropie menu

### ISSUE THREAD

**Issue by stsfin** [petrockblog/RetroPie-Setup#775]
Please add rpi-update to the retropie menu, since raspi-config allready is under this menu, the kernel update script could also be run from there...

**Comment by joolswills** [comment]
Not sure this is a good idea as rpi-update should not really be used in general, unless a user needs to test a bleeding edge kernel or roll back. New kernels are packaged up and included in Raspbian, and they should be used over rpi-update.

http://www.raspberrypi.org/forums/viewtopic.php?p=442642#p442642

**Comment by stsfin** [comment]
Yeah true. lets close this.
