### ISSUE TITLE
(GBA/GPSP) goldensun the lost ages starts right but...

### ISSUE THREAD

**Issue by screamindynomit** [petrockblog/RetroPie-Setup#803]
after loading up it gets to the point were dialog is about to happenin i think the 3rd cutscene  its like someone did a soft reset and it gives you the gba boot sequence and you go thru the whole new game sequence again anyone have a solution?

**Comment by screamindynomit** [comment]
ps this is the only game so far that has done this and the rom runs fine on pc emulator

**Comment by ProxyCell** [comment]
please post this to the GPSP repo page:
https://github.com/DPRCZ/gpsp

**Comment by screamindynomit** [comment]
moved to 

https://github.com/DPRCZ/gpsp/issues/7
