### ISSUE TITLE
ES-Scraper not saving metadata edits

### ISSUE THREAD

**Issue by HerbFargus** [petrockblog/RetroPie-Setup#807]
I know that this pertains to emulationstation but this issue may be retropie specific to emulationstation:

Quite a few people have mentioned their edits to metadata have not been saved:

http://blog.petrockblock.com/forums/topic/game-metadata-edits-not-saved/

http://blog.petrockblock.com/forums/topic/scraping-data-not-saved-in-es/

The only way I've been able to get manual edits to save is if I select quit emulationstation in the quit menu rather than shutdown or restart. Otherwise nothing is saved. Is there a way for edits to be written without needed a clean exit?

to reproduce- manually edit the metadata of a game within emulationstation and either shutdown or reboot- upon reboot it will be as if you made no changes.

**Comment by gizmo98** [comment]
I think emulationstation (over)writes gamelists.xmls on exit. If you have not the permission to edit a  gamelist.xml emulationstation throws an error on exit.

**Comment by HerbFargus** [comment]
Is there a specific way to check/get  permissions to edit gamelist.xml?

**Comment by Tele42** [comment]
I reported this over at https://github.com/Aloshi/EmulationStation/issues/432.

**Comment by gizmo98** [comment]
@herbfargus. This was only an example. Emulationstation seems to load all gamelists at startup and writes them back at exit. So if emulationstation is running and you modify a gamelist any modification will be overwritten.

**Comment by Tele42** [comment]
I think @HerbFargus is saying manual entries via emulation station's gui, not directly editing the gamelist.xml files.

**Comment by HerbFargus** [comment]
@Tele42 is right- I'm referring to manual edits via the emulation station GUI.

**Comment by HerbFargus** [comment]
Closing as it is an issue best resolved through emulationstation.

**Comment by x-manx** [comment]
Just restart the system instead of shutting it down.
