### ISSUE TITLE
[new feature] wifi editing tool in retropie menu

### ISSUE THREAD

**Issue by HerbFargus** [petrockblog/RetroPie-Setup#811]
It would be helpful to have a WiFi editing tool in the retropie menu (something like wpa-gui).

http://blog.petrockblock.com/forums/topic/wifi-editing-tool-from-retropie-setup-or-emulationstation

**Comment by free5ty1e** [comment]
I've been using wicd-curses, launched from a bash script in EmulationStation.  Works pretty well.

**Comment by HerbFargus** [comment]
Worked great for me- if it's added as a module in the retropie menu I'd be more than happy to put a quick tutorial for it on the wiki

**Comment by HerbFargus** [comment]
added to the source code. thanks for the idea @free5ty1e!

**Comment by free5ty1e** [comment]
no prob!  :D
