### ISSUE TITLE
stop configs being overwritten/updated after binaries update

### ISSUE THREAD

**Issue by InsecureSpike** [petrockblog/RetroPie-Setup#814]
is there anyway to stop configs being overwritten/updated when doing a binaries update?

`/opt/retropie/configs`

just done an update and my shader paths have been rewritten, how can i prevent this in the future?

thanks

**Comment by joolswills** [comment]
I will make sure it checks if set, and skip if it is.

**Comment by InsecureSpike** [comment]
thank you

**Comment by joolswills** [comment]
fixed in bc7f384749266e8ffdc024282cb2ea922ef6f125
