### ISSUE TITLE
libretro-fuse in Retropie 3 beta?

### ISSUE THREAD

**Issue by josh-long-** [petrockblog/RetroPie-Setup#857]
I would like to use this emulator in my Pi2 with Retropie 3 beta because I see that it has a virtual keyboard that is usefull for me. Any help how to achieve this? or any way to get a virtual keyboard into spectrum emu.

Thanks!

**Comment by joolswills** [comment]
it is included - if your script is up to date it should show up in experimental.

**Comment by josh-long-** [comment]
Oh yeah! I find it, downloaded, installed and working like a charm.

Thank you!
